
const supa=window.supa||window.novaCreateSupabaseClient();
const s={me:null,role:"",otpTok:"",otpOk:false,lat:null,lng:null,wType:""};
let map=null,mk=null;
const q=(id)=>document.getElementById(id);
const lab=(r)=>r==="rider"?"Driver":r==="seller"?"Food Seller":r==="agent"?"Service Agent":"None";
const wType=(r)=>r==="rider"?"driver":r==="seller"?"seller":r==="agent"?"agent":"";
function bases(){const o=[];const p=v=>{v=String(v||"").trim().replace(/\/+$/g,"");if(v&&/^https?:\/\//i.test(v)&&!o.includes(v))o.push(v)};p(window.CONTEST_API_BASE||window.API_BASE||"");try{p(localStorage.getItem("contest_api_base"));p(localStorage.getItem("api_base"))}catch(_){ }if(/^https?:\/\//i.test(location.origin||""))p(location.origin);p("https://novagapp-mart.onrender.com");return o}
async function g(path){for(const b of bases()){try{const r=await fetch(b+path,{cache:"no-store"});const j=await r.json().catch(()=>null);if(r.ok&&j?.ok)return j}catch(_){ }}return null}
async function p(path,body){for(const b of bases()){try{const r=await fetch(b+path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body||{})});const j=await r.json().catch(()=>null);if(r.ok&&j?.ok)return j;if(j?.error)return {ok:false,error:String(j.error||"api_error"),message:String(j.message||"")}}catch(_){ }}return {ok:false,error:"api_unreachable"}}
function phone(v){v=String(v||"").trim();if(v.startsWith("+"))return v.replace(/[^\d+]/g,"");const d=v.replace(/\D/g,"");if(d.length===10)return "+91"+d;if(d.length>=11&&d.length<=15)return "+"+d;return v}
function sel(r){s.role=r;s.wType=wType(r);s.otpTok="";s.otpOk=false;q("sr").textContent=lab(r);["rr","rs","ra"].forEach(id=>q(id).classList.remove("a"));if(r==="rider")q("rr").classList.add("a");if(r==="seller")q("rs").classList.add("a");if(r==="agent")q("ra").classList.add("a");q("fr").classList.toggle("hide",r!=="rider");q("fs").classList.toggle("hide",r!=="seller");q("fa").classList.toggle("hide",r!=="agent");q("os").textContent="OTP reset. Send again."}
function im(){if(map)return;map=L.map("m",{zoomControl:true}).setView([18.5204,73.8567],13);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(map);map.on("click",e=>loc(Number(e.latlng.lat),Number(e.latlng.lng),true))}
async function rev(lat,lng){try{const u=new URL("https://nominatim.openstreetmap.org/reverse");u.searchParams.set("format","jsonv2");u.searchParams.set("addressdetails","1");u.searchParams.set("zoom","18");u.searchParams.set("lat",String(lat));u.searchParams.set("lon",String(lng));const r=await fetch(u.toString(),{cache:"no-store",headers:{"Accept":"application/json","Accept-Language":"en-IN,en;q=0.9"}});if(!r.ok)return "";const d=await r.json().catch(()=>null);const a=d?.address||{};return ([a.road||a.neighbourhood||a.suburb||"",a.city||a.town||a.village||a.county||"",a.state||"",a.postcode||""].filter(Boolean).join(", ")||String(d?.display_name||"")).slice(0,180)}catch(_){return ""}}
async function loc(lat,lng,c){if(!Number.isFinite(lat)||!Number.isFinite(lng))return;s.lat=lat;s.lng=lng;if(!mk){mk=L.marker([lat,lng],{draggable:true}).addTo(map);mk.on("dragend",()=>{const p=mk.getLatLng();loc(Number(p.lat),Number(p.lng),false)})}else mk.setLatLng([lat,lng]);if(c&&map)map.setView([lat,lng],Math.max(15,map.getZoom()));const a=await rev(lat,lng);if(a)q("ad").value=a}
async function gps(){im();if(!navigator.geolocation){q("gs").textContent="GPS unsupported";return}q("gs").textContent="Detecting GPS...";navigator.geolocation.getCurrentPosition(async pos=>{const lat=Number(pos?.coords?.latitude),lng=Number(pos?.coords?.longitude),acc=Math.round(Number(pos?.coords?.accuracy||0));if(!Number.isFinite(lat)||!Number.isFinite(lng)){q("gs").textContent="GPS read failed";return}await loc(lat,lng,true);q("gs").textContent=`GPS locked (${acc}m)`},err=>{q("gs").textContent=`Permission required (${String(err?.message||"denied")})`},{enableHighAccuracy:true,timeout:20000,maximumAge:0})}
async function me(){const {data}=await supa.auth.getSession();s.me=data?.session?.user||null;if(!s.me){location.href="login.html";return null}q("u").textContent=`${s.me.email||"Logged in"} (${s.me.id})`;q("nm").value=String(s.me?.user_metadata?.full_name||s.me?.user_metadata?.name||"").slice(0,80);if(s.me?.phone)q("ph").value=String(s.me.phone||"").slice(0,30);return s.me}
async function sendOtp(){const u=await me();if(!u)return;if(!s.role){alert("Select role first");return}const ph=phone(q("ph").value);if(!ph){alert("Enter valid phone");return}q("ph").value=ph;q("os").textContent="Sending OTP...";const out=await p("/api/local/provider/otp/send",{user_id:u.id,phone:ph});if(!out?.ok){q("os").textContent=`OTP failed: ${String(out?.error||"send_failed")}`;return}s.otpTok=String(out.otp_token||"");s.otpOk=false;q("os").textContent=`OTP sent (${String(out.delivery||"in_app")})`;if(out.otp_preview)alert(`OTP preview: ${out.otp_preview}`)}
async function verifyOtp(){const u=await me();if(!u)return;if(!s.otpTok){alert("Send OTP first");return}const otp=String(q("otp").value||"").trim();if(!/^\d{6}$/.test(otp)){alert("Enter 6 digit OTP");return}const out=await p("/api/local/provider/otp/verify",{user_id:u.id,otp_token:s.otpTok,otp});if(!out?.ok){s.otpOk=false;q("os").textContent=`OTP verify failed: ${String(out?.error||"invalid")}`;return}s.otpOk=true;q("os").textContent="OTP verified"}
async function fee(role){const u=await me();if(!u)throw new Error("login_required");const o=await p("/api/local/role/fee/order",{user_id:u.id,role});if(!o?.ok||!o?.order?.razorpay_order_id)throw new Error(String(o?.error||"fee_order_failed"));if(typeof window.Razorpay!=="function")throw new Error("razorpay_sdk_missing");const nm=String(q("nm").value||"").trim(),ph=String(q("ph").value||"").trim();return new Promise((res,rej)=>{const rz=new window.Razorpay({key:String(o.order.key_id||""),amount:Number(o.order.amount_paise||50000),currency:"INR",name:"NovaGapp",description:`${lab(role)} provider fee`,order_id:String(o.order.razorpay_order_id||""),prefill:{name:nm,email:s.me?.email||"",contact:ph},handler:async r=>{const v=await p("/api/local/role/fee/verify",{user_id:u.id,role,razorpay_order_id:String(r?.razorpay_order_id||""),razorpay_payment_id:String(r?.razorpay_payment_id||""),razorpay_signature:String(r?.razorpay_signature||"")});if(!v?.ok){rej(new Error(String(v?.error||"fee_verify_failed")));return}res({payment_ref:String(r?.razorpay_payment_id||"")})},modal:{ondismiss:()=>rej(new Error("payment_cancelled"))}});rz.open()})}
async function upDriver(uid,nm,ph){const e=await g(`/api/local/listings/for-owner?user_id=${encodeURIComponent(uid)}&listing_type=ride`);const ex=Array.isArray(e?.listings)?e.listings[0]:null;const body={user_id:uid,listing_type:"ride",store_name:nm,phone:ph,lat:s.lat,lng:s.lng,open_now:true,ride_vehicle_type:String(q("vtype").value||"auto"),vehicle_number:String(q("vno").value||"").trim(),base_fare_inr:Number(q("bf").value||0),per_km_rate_inr:Number(q("pk").value||0),per_min_rate_inr:Number(q("pm").value||0),service_radius_km:Number(q("rrad").value||5),documents_url:String(q("docs").value||"").trim()};if(!body.vehicle_number)return {ok:false,error:"vehicle_number_required"};if(ex?.id)return p("/api/local/listings/update",Object.assign({listing_id:String(ex.id)},body));return p("/api/local/listings/create",body)}
async function upSeller(uid,ph){const type=String(q("stype").value||"food");const name=String(q("sn").value||"").trim();if(!name)return {ok:false,error:"store_name_required"};const e=await g(`/api/local/listings/for-owner?user_id=${encodeURIComponent(uid)}&listing_type=${encodeURIComponent(type)}`);const ex=Array.isArray(e?.listings)?e.listings[0]:null;const body={user_id:uid,listing_type:type,store_name:name,phone:ph,image_url:String(q("si").value||"").trim(),lat:s.lat,lng:s.lng,open_now:true,delivery_charge_inr:Number(q("dc").value||0),minimum_order_inr:Number(q("mo").value||0),open_time:String(q("ot").value||"").trim(),close_time:String(q("ct").value||"").trim(),self_delivery:true};if(ex?.id)return p("/api/local/listings/update",Object.assign({listing_id:String(ex.id)},body));return p("/api/local/listings/create",body)}
async function upAgent(uid,ph){const title=String(q("at").value||"").trim();if(!title)return {ok:false,error:"agent_title_required"};return p("/api/local/agents/create",{user_id:uid,service_category:String(q("ac").value||"electrician"),title,phone:ph,price_per_visit_inr:Number(q("av").value||0),per_hour_rate_inr:Number(q("ah").value||0),experience_years:Number(q("ae").value||0),service_radius_km:Number(q("ar").value||5),available_now:String(q("aa").value||"true")==="true",lat:s.lat,lng:s.lng})}
async function activate(){const u=await me();if(!u)return;if(!s.role){alert("Select role");return}if(!s.otpOk||!s.otpTok){alert("OTP verify first");return}if(!Number.isFinite(s.lat)||!Number.isFinite(s.lng)){alert("Set GPS location first");return}const nm=String(q("nm").value||"").trim(),ph=phone(q("ph").value);if(!nm||!ph){alert("Name and phone required");return}q("as").textContent="Processing...";try{const pay=await fee(s.role);const en=await p("/api/local/role/enroll",{user_id:u.id,role:s.role,display_name:nm,phone:ph,fee_paid:true,payment_ref:String(pay?.payment_ref||""),otp_token:s.otpTok});if(!en?.ok)throw new Error(String(en?.error||"role_enroll_failed"));let pr={ok:true};if(s.role==="rider")pr=await upDriver(u.id,nm,ph);if(s.role==="seller")pr=await upSeller(u.id,ph);if(s.role==="agent")pr=await upAgent(u.id,ph);if(!pr?.ok)throw new Error(String(pr?.error||"profile_update_failed"));q("as").textContent=`${lab(s.role)} activated`;await roles();await rw();alert(`${lab(s.role)} activated`)}catch(e){q("as").textContent=`Failed: ${String(e?.message||e||"unknown")}`}}
async function roles(){if(!s.me)return;const out=await g(`/api/local/roles?user_id=${encodeURIComponent(s.me.id)}`);const rows=Array.isArray(out?.roles)?out.roles:[];const b=q("rb");b.innerHTML="";if(!rows.length){b.innerHTML='<span class="mut">No active role</span>';return}rows.forEach(r=>{const p=document.createElement("span");p.className="pill";p.textContent=`${lab(String(r.role||""))} | ${String(r.status||"active")}`;b.appendChild(p)})}
async function rw(){if(!s.me){q("wt").textContent="Login required";return}const t=s.wType||wType(s.role);if(!t){q("wt").textContent="Select role";return}const w=await g(`/api/local/wallet?owner_user_id=${encodeURIComponent(s.me.id)}&owner_type=${encodeURIComponent(t)}`);const row=w?.wallet||(Array.isArray(w?.wallets)?w.wallets[0]:null);const tx=await g(`/api/local/transactions?user_id=${encodeURIComponent(s.me.id)}&owner_type=${encodeURIComponent(t)}&limit=5`);q("wt").textContent=row?`${t} wallet: INR ${Number(row.balance_inr||0).toFixed(2)} | tx: ${Array.isArray(tx?.transactions)?tx.transactions.length:0}`:`${t} wallet not found`}
function bind(){q("send").onclick=()=>sendOtp().catch(()=>{});q("ver").onclick=()=>verifyOtp().catch(()=>{});q("gps").onclick=()=>gps().catch(()=>{});q("act").onclick=()=>activate().catch(()=>{})}
(async()=>{im();bind();await me();await roles();})();
